name: 'Terraform'

on: workflow_dispatch

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  TF_VAR_project: ${{ secrets.TF_VAR_PROJECT }}
  TF_VAR_bucket: ${{ secrets.TF_VAR_BUCKET }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        run: terraform init
#      - name: Terraform apply
#        run: terraform apply -auto-aprove -input=false